### ISSUE TITLE
Failed Test: test_content_tag_soup (tests.test_reconstitute.ReconstituteTest)

### ISSUE THREAD

**Issue by hossman** [rubys/venus#14]
# Summary

I cloned the git repo as of "9de21094a8cf565bdfcf75688e121a5ad1f5397b" and tried to follow the general instructions but encountered an error with "python runtests.py"  Full output and the details i could think of that might be relevant (i'm not really a python guy) are below...
# Output

```
hossman@bester:~/venus [master] $ python runtests.py
Genshi is not available => can't test genshi filters
Redland RDF is not available => can't test FOAF reading lists
................................................................................................................E............................................................................................................
======================================================================
ERROR: test_content_tag_soup (tests.test_reconstitute.ReconstituteTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hossman/venus/tests/test_reconstitute.py", line 43, in <lambda>
    func = lambda self, name=root: self.eval(name)
  File "/home/hossman/venus/tests/test_reconstitute.py", line 26, in eval
    results = feedparser.parse(data)
  File "/home/hossman/venus/planet/vendor/feedparser.py", line 3602, in parse
    feedparser.feed(data)
  File "/home/hossman/venus/planet/vendor/feedparser.py", line 1723, in feed
    sgmllib.SGMLParser.feed(self, data)
  File "/usr/lib/python2.6/sgmllib.py", line 104, in feed
    self.goahead(0)
  File "/usr/lib/python2.6/sgmllib.py", line 143, in goahead
    k = self.parse_endtag(i)
  File "/usr/lib/python2.6/sgmllib.py", line 320, in parse_endtag
    self.finish_endtag(tag)
  File "/usr/lib/python2.6/sgmllib.py", line 360, in finish_endtag
    self.unknown_endtag(tag)
  File "/home/hossman/venus/planet/vendor/feedparser.py", line 580, in unknown_endtag
    method()
  File "/home/hossman/venus/planet/vendor/feedparser.py", line 1540, in _end_content
    value = self.popContent('content')
  File "/home/hossman/venus/planet/vendor/feedparser.py", line 867, in popContent
    value = self.pop(tag)
  File "/home/hossman/venus/planet/vendor/feedparser.py", line 782, in pop
    mfresults = _parseMicroformats(output, self.baseuri, self.encoding)
  File "/home/hossman/venus/planet/vendor/feedparser.py", line 2279, in _parseMicroformats
    p = _MicroformatsParser(htmlSource, baseURI, encoding)
  File "/home/hossman/venus/planet/vendor/feedparser.py", line 1884, in __init__
    self.document = BeautifulSoup.BeautifulSoup(data)
  File "/usr/lib/pymodules/python2.6/BeautifulSoup.py", line 1499, in __init__
    BeautifulStoneSoup.__init__(self, *args, **kwargs)
  File "/usr/lib/pymodules/python2.6/BeautifulSoup.py", line 1230, in __init__
    self._feed(isHTML=isHTML)
  File "/usr/lib/pymodules/python2.6/BeautifulSoup.py", line 1263, in _feed
    self.builder.feed(markup)
  File "/usr/lib/python2.6/HTMLParser.py", line 108, in feed
    self.goahead(0)
  File "/usr/lib/python2.6/HTMLParser.py", line 148, in goahead
    k = self.parse_starttag(i)
  File "/usr/lib/python2.6/HTMLParser.py", line 226, in parse_starttag
    endpos = self.check_for_whole_start_tag(i)
  File "/usr/lib/python2.6/HTMLParser.py", line 301, in check_for_whole_start_tag
    self.error("malformed start tag")
  File "/usr/lib/python2.6/HTMLParser.py", line 115, in error
    raise HTMLParseError(message, self.getpos())
HTMLParseError: malformed start tag, at line 1, column 14

----------------------------------------------------------------------
Ran 221 tests in 19.080s

FAILED (errors=1)
```
# System Info

```
hossman@bester:~/venus [master] $ uname -a
Linux bester 2.6.31-23-generic #75-Ubuntu SMP Fri Mar 18 18:16:06 UTC 2011 x86_64 GNU/Linux
hossman@bester:~/venus [master] $ python --version
Python 2.6.4
hossman@bester:~/venus [master] $ dpkg --list | grep python
ii  libpython2.6                         2.6.4-0ubuntu3                             Shared Python runtime library (version 2.6)
ii  python                               2.6.4-0ubuntu1                             An interactive high-level object-oriented la
ii  python-apport                        1.9.3-0ubuntu4.2                           apport crash report handling library
ii  python-apt                           0.7.13.2ubuntu4                            Python interface to libapt-pkg
ii  python-aptdaemon                     0.10+bzr264-0ubuntu1                       Python module for the server and client of a
ii  python-aptdaemon-gtk                 0.10+bzr264-0ubuntu1                       Python GTK+ widgets to run an aptdaemon clie
ii  python-avahi                         0.6.25-1ubuntu5.3                          Python utility package for Avahi
ii  python-beautifulsoup                 3.1.0.1-2                                  error-tolerant HTML parser for Python
ii  python-brlapi                        4.0-7ubuntu2                               Python bindings for BrlAPI
ii  python-cairo                         1.8.6-1ubuntu1                             Python bindings for the Cairo vector graphic
ii  python-central                       0.6.11ubuntu9                              register and build utility for Python packag
ii  python-cherrypy3                     3.1.2-1                                    Python web development framework - version 3
ii  python-chm                           0.8.4-1                                    Python binding for CHMLIB
ii  python-clientform                    0.2.10-2                                   module for handling HTML forms on the client
ii  python-configglue                    0.2dev-0ubuntu2                            Glues together optparse.OptionParser and Con
ii  python-couchdb                       0.6-1                                      library for working with Apache CouchDB
ii  python-crypto                        2.0.1+dfsg1-4ubuntu1                       cryptographic algorithms and protocols for P
ii  python-cssutils                      0.9.5.1-1                                  CSS Cascading Style Sheets parser and builde
ii  python-cups                          1.9.46-0ubuntu2                            Python bindings for CUPS
ii  python-cupshelpers                   1.1.12+git20090826-0ubuntu8                Python modules for printer configuration wit
ii  python-dateutil                      1.4.1-3                                    powerful extensions to the standard datetime
ii  python-dbus                          0.83.0-1ubuntu2                            simple interprocess messaging system (Python
ii  python-debian                        0.1.14ubuntu1                              Python modules to work with Debian-related d
ii  python-desktopcouch                  0.5-0ubuntu1                               Python Desktop CouchDB
ii  python-desktopcouch-records          0.5-0ubuntu1                               Desktop CouchDB Records API
ii  python-dev                           2.6.4-0ubuntu1                             Header files and a static library for Python
ii  python-django                        1.1.1-1ubuntu1.2                           High-level Python web development framework
ii  python-django-tagging                0.2.1+svn154-0ubuntu2                      A generic tagging application for Django pro
ii  python-encutils                      0.9.5.1-1                                  Encoding detection collection for Python
ii  python-fstab                         1.4-0ubuntu1                               read, manipulate, and write /etc/fstab files
ii  python-gconf                         2.28.0-0ubuntu1                            Python bindings for the GConf configuration 
ii  python-gdbm                          2.6.3-0ubuntu1                             GNU dbm database support for Python
ii  python-glade2                        2.16.0-0ubuntu1                            GTK+ bindings: Glade support
ii  python-gmenu                         2.28.0.1-0ubuntu1                          an implementation of the freedesktop menu sp
ii  python-gnome2                        2.28.0-0ubuntu1                            Python bindings for the GNOME desktop enviro
ii  python-gnomeapplet                   2.28.0-0ubuntu1                            Python bindings for the GNOME panel applet l
ii  python-gnomecanvas                   2.28.0-0ubuntu1                            Python bindings for gnomecanvas (debug exten
ii  python-gnomekeyring                  2.28.0-0ubuntu1                            Python bindings for the GNOME keyring librar
ii  python-gnupginterface                0.3.2-9ubuntu2                             Python interface to GnuPG (GPG)
ii  python-gobject                       2.18.0-0ubuntu2                            Python bindings for the GObject library
ii  python-gst0.10                       0.10.17-1                                  generic media-playing framework (Python bind
ii  python-gtk2                          2.16.0-0ubuntu1                            Python bindings for the GTK+ widget set
ii  python-gtkhtml2                      2.25.3-3ubuntu1.9.10.1                     Python bindings for the GtkHTML 2 library
ii  python-gtksourceview2                2.8.0-1                                    Python bindings for the GtkSourceView widget
ii  python-httplib2                      0.4.0-0ubuntu2                             A comprehensive HTTP client library written 
ii  python-ibus                          1.2.0.20090927-2ubuntu2                    New input method framework using dbus
ii  python-imaging                       1.1.6-3ubuntu1                             Python Imaging Library
ii  python-launchpad-integration         0.1.26                                     library for launchpad integration
ii  python-launchpadlib                  1.5.1-0ubuntu1                             Launchpad web services client library
ii  python-lazr-restfulclient            0.9.3-0ubuntu3                             client for lazr.restful-based web services
ii  python-lazr-uri                      1.0-0ubuntu1                               library for parsing, manipulating, and gener
ii  python-libxml2                       2.7.5.dfsg-1ubuntu1.2                      Python bindings for the GNOME XML library
ii  python-louis                         1.7.0-1ubuntu1                             Python bindings for liblouis
ii  python-lxml                          2.1.5-1ubuntu2                             pythonic binding for the libxml2 and libxslt
ii  python-mechanize                     0.1.11-0ubuntu1                            stateful programmatic web browsing
ii  python-minimal                       2.6.4-0ubuntu1                             A minimal subset of the Python language (def
ii  python-newt                          0.52.10-4ubuntu1                           A NEWT module for Python
ii  python-notify                        0.1.1-2build2                              Python bindings for libnotify
ii  python-numpy                         1:1.3.0-3                                  Numerical Python adds a fast array facility 
ii  python-oauth                         1.0a~svn1124-0ubuntu2                      implementation of the OAuth protocol
ii  python-openoffice                    0.1+r34-1                                  Python libraries for interacting with OpenOf
ii  python-openssl                       0.9-1                                      Python wrapper around the OpenSSL library
ii  python-pam                           0.4.2-12ubuntu3                            A Python interface to the PAM library
ii  python-papyon                        0.4.3-1ubuntu1                             MSN client library written in Python
ii  python-pkg-resources                 0.6c9-0ubuntu5                             Package Discovery and Resource Access using 
ii  python-problem-report                1.9.3-0ubuntu4.2                           Python library to handle problem reports
ii  python-protobuf                      2.0.3-2.2ubuntu2                           Python bindings for protocol buffers
ii  python-pyatspi                       1.28.1-0ubuntu1                            Assistive Technology Service Provider Interf
ii  python-pyinotify                     0.8.6-2ubuntu2                             simple Linux inotify Python bindings
ii  python-pyorbit                       2.24.0-0ubuntu3                            A Python language binding for the ORBit2 COR
ii  python-pypdf                         1.12-2                                     PDF toolkit implemented solely in Python
ii  python-qt4                           4.6-1                                      Python bindings for Qt4
ii  python-rdflib                        2.4.0-5ubuntu1                             RDF library containing an RDF triple store a
ii  python-renderpm                      2.3-0ubuntu1                               python low level render interface
ii  python-reportlab                     2.3-0ubuntu1                               ReportLab library to create PDF documents us
ii  python-reportlab-accel               2.3-0ubuntu1                               C coded extension accelerator for the Report
ii  python-rsvg                          2.28.0-0ubuntu1                            Python bindings for the RSVG library
ii  python-serial                        2.3-1                                      pyserial - module encapsulating access for t
ii  python-sexy                          0.1.9-1ubuntu2                             python language bindings for libsexy
ii  python-simplejson                    2.0.9-1                                    Simple, fast, extensible JSON encoder/decode
ii  python-sip4                          4.9.1-snapshot-20091015-0ubuntu1           Python/C++ bindings generator runtime librar
ii  python-smbc                          1.0.6-0ubuntu2                             Python bindings for Samba clients (libsmbcli
ii  python-software-properties           0.75.4                                     manage the repositories that you install sof
ii  python-speechd                       0.6.7+git20090914~unofficial-0ubuntu4      Python interface to Speech Dispatcher
ii  python-support                       1.0.3ubuntu1                               automated rebuilding support for Python modu
ii  python-telepathy                     0.15.11-1                                  Python language bindings for telepathy
ii  python-tk                            2.6.3-0ubuntu1                             Tkinter - Writing Tk applications with Pytho
ii  python-twisted-bin                   8.2.0-3                                    Event-based framework for internet applicati
ii  python-twisted-core                  8.2.0-3                                    Event-based framework for internet applicati
ii  python-twisted-names                 8.2.0-1ubuntu2                             A DNS protocol implementation with client an
ii  python-twisted-web                   8.2.0-2ubuntu1                             An HTTP protocol implementation together wit
ii  python-ubuntuone-client              1.0.3-0ubuntu1                             Ubuntu One client Python libraries
ii  python-ubuntuone-storageprotocol     1.0.1-0ubuntu1                             Python library for Ubuntu One file storage a
ii  python-uniconvertor                  1.1.4-1                                    Universal vector graphics translator
ii  python-uno                           1:3.2.0-7ubuntu1~karmic1                   Python-UNO bridge
ii  python-virtkey                       0.50ubuntu2                                Library to emulate keyboard keypresses.
ii  python-vte                           1:0.22.2-0ubuntu2.1                        Python bindings for the VTE widget set
ii  python-wadllib                       1.1.2-0ubuntu1                             Python library for navigating WADL files
ii  python-webkit                        1.1.5-1                                    WebKit/Gtk Python bindings
ii  python-xapian                        1.0.14-1build1                             Xapian search engine interface for Python
ii  python-xdg                           0.15-1.1ubuntu5                            A python library to access freedesktop.org s
ii  python-xkit                          0.4.2                                      library for the manipulation of the xorg.con
ii  python-zope.interface                3.5.2-1                                    Zope 3 Interface Infrastructure
ii  python2.4                            2.4.6-1ubuntu3.2.9.10.1                    An interactive high-level object-oriented la
ii  python2.4-minimal                    2.4.6-1ubuntu3.2.9.10.1                    A minimal subset of the Python language (ver
ii  python2.5                            2.5.4-1ubuntu6.1                           An interactive high-level object-oriented la
ii  python2.5-minimal                    2.5.4-1ubuntu6.1                           A minimal subset of the Python language (ver
ii  python2.6                            2.6.4-0ubuntu3                             An interactive high-level object-oriented la
ii  python2.6-dev                        2.6.4-0ubuntu3                             Header files and a static library for Python
ii  python2.6-minimal                    2.6.4-0ubuntu3                             A minimal subset of the Python language (ver

```

**Comment by hossman** [comment]
FYI: attempted to reproduce this (with same SHA) on another machine (www service provider) did not produce these test errors...

```
hossman@giedi:~/venus$ python runtests.py
Redland RDF is not available => can't test FOAF reading lists
...............................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 223 tests in 3.903s

OK
hossman@giedi:~/venus$ uname -a
Linux giedi 2.6.32.45-grsec-2.2.2-r3 #8 SMP Mon Oct 10 13:33:17 PDT 2011 x86_64 GNU/Linux
hossman@giedi:~/venus$ python --version
Python 2.6.6
hossman@giedi:~/venus$ dpkg --list | grep python
ii  libpython2.6                                                2.6.6-8+b1                           Shared Python runtime library (version 2.6)
ii  python                                                      2.6.6-3+squeeze6                     interactive high-level object-oriented language (default version)
ii  python-all                                                  2.6.6-3+squeeze6                     package depending on all supported Python runtime versions
ii  python-all-dev                                              2.6.6-3+squeeze6                     package depending on all supported Python development packages
ii  python-central                                              0.6.16+nmu1                          register and build utility for Python packages
ii  python-dev                                                  2.6.6-3+squeeze6                     header files and a static library for Python (default)
ii  python-django                                               1.2.3-3+squeeze2                     High-level Python web development framework
ii  python-doc                                                  2.6.6-3+squeeze6                     documentation for the high-level object-oriented language Python
ii  python-egenix-mxdatetime                                    3.1.3-4                              date and time handling routines for Python
ii  python-egenix-mxproxy                                       3.1.3-4                              generic proxy wrapper type for Python
ii  python-egenix-mxqueue                                       3.1.3-4                              fast and memory-efficient queue for Python
ii  python-egenix-mxstack                                       3.1.3-4                              fast and memory-efficient stack for Python
ii  python-egenix-mxtexttools                                   3.1.3-4                              fast text processing tools for Python
ii  python-egenix-mxtools                                       3.1.3-4                              collection of additional builtins for Python
ii  python-elementtree                                          1.2.6-1                              <insert up to 60 chars description>
ii  python-examples                                             2.6.6-3+squeeze6                     examples for the Python language (default version)
ii  python-gdbm                                                 2.6.6-1                              GNU dbm database support for Python
ii  python-genshi                                               0.6-1                                Python XML-based template engine
ii  python-gnuplot                                              1.8-1.1                              A Python interface to the gnuplot plotting program
ii  python-imaging                                              1.1.7-2                              Python Imaging Library
ii  python-imaging-doc                                          1.1.7-2                              Examples for the Python Imaging Library
ii  python-imaging-tk                                           1.1.7-2                              Python Imaging Library - ImageTk Module
ii  python-irclib                                               0.4.8-1                              IRC client library for Python
ii  python-libxml2                                              2.7.8.dfsg-2+squeeze1                Python bindings for the GNOME XML library
ii  python-libxslt1                                             1.1.26-6                             Python bindings for libxslt1
ii  python-minimal                                              2.6.6-3+squeeze6                     minimal subset of the Python language (default version)
ii  python-mode                                                 1:5.1.0-1                            Python mode for GNU Emacs and XEmacs
ii  python-mongodb                                              1.3-2                                MongoDB driver
ii  python-mysqldb                                              1.2.2-10+b1                          A Python interface to MySQL
ii  python-newt                                                 0.52.11-1                            A NEWT module for Python
ii  python-numpy                                                1:1.4.1-5                            Numerical Python adds a fast array facility to the Python language
ii  python-openssl                                              0.10-1                               Python wrapper around the OpenSSL library
ii  python-pkg-resources                                        0.6.14-4                             Package Discovery and Resource Access using pkg_resources
ii  python-pycurl                                               7.19.0-3+b1                          Python bindings to libcurl
ii  python-pygresql                                             1:4.0-2+b1                           PostgreSQL module for Python
ii  python-pysqlite2                                            2.6.0-1                              Python interface to SQLite 3
ii  python-selinux                                              2.0.96-1                             Python bindings to SELinux shared libraries
ii  python-semanage                                             2.0.45-1                             Python bindings  for SELinux policy management
ii  python-sepolgen                                             1.0.23-1                             A Python module used in SELinux policy generation
ii  python-setuptools                                           0.6.14-4                             Python Distutils Enhancements (setuptools compatibility)
ii  python-simplejson                                           2.1.1-1                              simple, fast, extensible JSON encoder/decoder for Python
ii  python-sqlite                                               1.0.1-7+b1                           python interface to SQLite 2
ii  python-subversion                                           1.6.12dfsg-6                         Python bindings for Subversion
ii  python-support                                              1.0.10                               automated rebuilding support for Python modules
ii  python-svn                                                  1.7.2-3                              A(nother) Python interface to Subversion
ii  python-swiginac                                             1.5.1.1-1                            Python interface to GiNaC
ii  python-tk                                                   2.6.6-1                              Tkinter - Writing Tk applications with Python
ii  python-unit                                                 1.4.1-16                             unit test framework for Python
ii  python-virtualenv                                           1.4.9-3                              Python virtual environment creator
ii  python-xapian                                               1.2.3-3                              Xapian search engine interface for Python
ii  python-xmpp                                                 0.4.1-cvs20080505.2                  Python library for communication with XMPP (Jabber) servers
ii  python-yaml                                                 3.09-5                               YAML parser and emitter for Python
ii  python2.5                                                   2.5.5-11                             An interactive high-level object-oriented language (version 2.5)
ii  python2.5-dev                                               2.5.5-11                             Header files and a static library for Python (v2.5)
ii  python2.5-minimal                                           2.5.5-11                             A minimal subset of the Python language (version 2.5)
ii  python2.6                                                   2.6.6-8+b1                           An interactive high-level object-oriented language (version 2.6)
ii  python2.6-dev                                               2.6.6-8+b1                           Header files and a static library for Python (v2.6)
ii  python2.6-doc                                               2.6.6-8                              Documentation for the high-level object-oriented language Python (v2.6)
ii  python2.6-examples                                          2.6.6-8                              Examples for the Python language (v2.6)
ii  python2.6-minimal                                           2.6.6-8+b1                           A minimal subset of the Python language (version 2.6)

```

**Comment by hossman** [comment]
Also verified that the test failure persists even after installing the python-genshi, python2.6-librdf, and python2.4-librdf .deb packages, that failure still happens.

**Comment by Cabalist** [comment]
Unable to reproduce and very old.
